"""Federated harness evolution: broadcast -> parallel local evolution -> aggregate -> repeat.

One federated round:
  1. BROADCAST  the current global harness to every client
  2. LOCAL      each client runs optimize.py on its own shard, starting from that global (parallel)
  3. AGGREGATE  the merger folds the K client harnesses back into one global
  4. VERIFY     the merged global must load and still run; otherwise ROLL BACK to the broadcast global

After T rounds the global harness is frozen. Scoring it on a held-out set is a separate step
(fed/evaluate.py) — nothing in this loop reads gold.

Rollback goes to the PREVIOUS GLOBAL, not to the best client. Picking a "best" client would need
accuracy we do not have at training time (no gold), and it would break the invariant the merger
depends on: every client in a round starts from one shared broadcast harness.
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

_ORIG_CWD = Path.cwd()          # importing bridge (below) chdirs into the evoluation dir; capture ours first

from ..evolve import AGENTS_DIR, MH_ROOT, PKG, PKG_DIR   # noqa: E402
from . import merge as M                                 # noqa: E402


def run_client(k, shard, global_name, run_name, args):
    """One client's local evolution = one optimize.py subprocess. Returns its result dict."""
    client_run = f"{run_name}_r{args._round}_c{k}"
    pairs = json.loads(Path(shard).read_text(encoding="utf-8"))["cross"]
    cmd = [
        sys.executable, "-u", "-m", f"{PKG}.optimize",
        "--cross-set", str(shard),
        "--initial-harness", global_name,
        "--run-name", client_run,
        "--batch-size", str(len(pairs)),          # whole shard = one batch -> --max-rounds is the local epoch count
        "--group", str(args.group),
        "--max-rounds", str(args.local_rounds),
        "--role-offset", str(k),            # spread search roles across clients, not within one
        "--proposer", "agentic",
        "--propose-timeout", str(args.propose_timeout),
        "--solve-timeout", str(args.solve_timeout),
        "--model", args.model,
    ]
    if args.bare_result:
        cmd += ["--bare-result", args.bare_result]
    if args.supervised:
        cmd += ["--supervised"]
    if args.specialist:
        cmd += ["--specialist"]
    if args.public_val:
        cmd += ["--public-val", str(args.public_val)]
    log_path = PKG_DIR / "logs" / f"{client_run}.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"   [client {k}] {len(pairs)} questions from {global_name} -> {client_run}", flush=True)
    started = time.monotonic()
    with open(log_path, "w", encoding="utf-8") as lf:
        proc = subprocess.run(cmd, cwd=str(MH_ROOT), stdout=lf, stderr=subprocess.STDOUT, text=True)
    dur = round(time.monotonic() - started, 1)
    res_path = PKG_DIR / "logs" / client_run / "result.json"
    if proc.returncode != 0 or not res_path.exists():
        print(f"   [client {k}] FAILED rc={proc.returncode} after {dur}s — see {log_path}", flush=True)
        return None
    res = json.loads(res_path.read_text(encoding="utf-8"))
    print(f"   [client {k}] done in {dur}s -> harness={res['final_harness']} "
          f"(local score {res['tt_correct']}/{res['tt_total']}, gold-scored for logging only)", flush=True)
    return {"client": k, "harness": res["final_harness"], "shard": str(shard),
            "trace_dir": str(PKG_DIR / "logs" / client_run / "traces" / "b0"),
            "local_correct": res["tt_correct"], "local_total": res["tt_total"],
            "run": client_run, "seconds": dur}


ROUTE_TEMPLATE = '''"""Delegation-composed global harness (auto-generated by fed_loop --aggregate route).

Aggregation by expert delegation, zero rewriting: questions on a client's home domain go to that client's
harness verbatim; everything else to the client that scored highest on the server's gate slice. Measured
motivation: every rule-level transfer (holistic/scoped/verbatim merger sessions) lost part of the experts'
home behaviour in rewriting; delegating the whole program is the zero-loss end of that spectrum and costs
no merger session at all.
"""
from ..harness_base import SQLHarness


class RouteHarness(SQLHarness):
    HOME = {home!r}
    DEFAULT = {default!r}

    def solve(self, question: str) -> str:
        import importlib
        name = self.HOME.get(self.db.db_id, self.DEFAULT)
        mod = importlib.import_module(f"{{__package__}}.{{name}}")
        cls = next(o for o in vars(mod).values()
                   if isinstance(o, type) and issubclass(o, SQLHarness) and o is not SQLHarness)
        inner = cls(self.db)
        try:
            return inner.solve(question)
        finally:
            self._trace = inner._trace
'''


def write_route(name, home, default):
    """Materialize the dispatch artifact. Mechanical — no LLM involved."""
    path = AGENTS_DIR / f"{name}.py"
    path.write_text(ROUTE_TEMPLATE.format(home=home, default=default), encoding="utf-8")
    return path


def smoke_samples(shards, n_per_shard=1):
    """A couple of real questions per shard, for the post-merge health check."""
    from .. import bridge
    out = []
    for shard in shards:
        pairs = json.loads(Path(shard).read_text(encoding="utf-8"))["cross"]
        for db_id, idx in pairs[:n_per_shard]:
            out.append((db_id, bridge.eval_questions(db_id)[idx].question))
    return out


def load_slice(path):
    """A cross-set slice -> ([(db_id, question)], [gold]). Same shape as training_set()."""
    from .. import bridge
    items, golds = [], []
    for db_id, idx in json.loads(Path(path).read_text(encoding="utf-8"))["cross"]:
        q = bridge.eval_questions(db_id)[idx]
        items.append((db_id, q.question))
        golds.append(bridge.gold_result(bridge.get_db(db_id), q.gold_sql))
    return items, golds


def training_set(shards):
    """Every training question across all shards, with its gold. -> ([(db_id, question_text)], [gold])"""
    from .. import bridge
    items, golds = [], []
    for shard in shards:
        for db_id, idx in json.loads(Path(shard).read_text(encoding="utf-8"))["cross"]:
            q = bridge.eval_questions(db_id)[idx]
            items.append((db_id, q.question))
            golds.append(bridge.gold_result(bridge.get_db(db_id), q.gold_sql))
    return items, golds


def measure(harness, items, golds, run_dir, timeout, workers=5):
    """Accuracy of `harness` over the whole training set. Used to accept or reject a merge.

    Per-question rows are written to <run_dir>/measure_<harness>.json. Keeping only the total was a
    mistake: when a merge is rejected the interesting question is WHICH questions it broke and what SQL
    it produced for them, and a bare count throws exactly that away.
    """
    from .. import bridge
    from ..optimize import isolated_solve

    def one(j):
        db_id, qtext = items[j]
        out = isolated_solve(run_dir, harness, db_id, qtext, timeout, f"measure_{harness}_{j}")
        res = out.get("result") or {}
        # `qtext` is the stable key. Row ORDER differs between writers — fed_loop walks shards, evaluate
        # walks the slice — so anything that joins two of these files by position silently compares
        # different questions. (It did: a "merge solves what no client solves" analysis was built on
        # mismatched rows before this was caught.) Join on `q`, never on `i`.
        return {"i": j, "db_id": db_id, "q": qtext.partition("\nHint:")[0].strip()[:200],
                "status": out.get("status"), "exec_ok": res.get("ok"),
                "correct": bool(res.get("ok")) and bridge.is_correct(res, golds[j]),
                "sql": " ".join(str(out.get("sql") or "").split())[:400]}

    with ThreadPoolExecutor(max_workers=workers) as pool:
        rows = sorted(pool.map(one, range(len(items))), key=lambda r: r["i"])
    Path(run_dir).mkdir(parents=True, exist_ok=True)
    (Path(run_dir) / f"measure_{harness}.json").write_text(json.dumps(rows, indent=2), encoding="utf-8")
    return rows


def client_gains(results):
    """What each client newly solved relative to the harness that was broadcast to it.

    Each client already computed this on its own shard when it selected a candidate, so it costs nothing
    here. It is the signal the merger was missing: previously it had to infer a mechanism's worth by
    reading code and traces, while the run as a whole showed that the union of the round's harnesses
    solved several questions no single merged global kept. Naming those questions makes preserving them
    a checkable requirement instead of a hope.
    """
    blocks = []
    for r in results:
        vpath = PKG_DIR / "logs" / r["run"] / "shard_verdicts_b0.json"
        if not vpath.exists():
            continue
        v = json.loads(vpath.read_text(encoding="utf-8"))
        fixed = [q for q in v["questions"] if q["delta"] == "fixed"]
        broke = [q for q in v["questions"] if q["delta"] == "broke"]
        if not fixed and not broke:
            continue
        lines = [f"- client {r['client']} (`{r['harness']}`):"]
        for q in fixed:
            lines.append(f"    NEWLY SOLVED  [{q['db_id']}] {q['question'][:130]}")
        for q in broke:
            lines.append(f"    REGRESSED     [{q['db_id']}] {q['question'][:130]}")
        blocks.append("\n".join(lines))
    return "\n".join(blocks)


def compare(new_rows, old_rows):
    """-> (fixed_indices, broke_indices). Per-question, not totals.

    Totals are the wrong comparator here: repeat measurements of the SAME harness on the SAME questions
    move by 2-3, which is the size of the effects being judged. Most questions agree between any two
    harnesses, so counting which ones flipped is far less noise-sensitive than differencing two sums —
    and "fixed 3, broke 5" carries information that "-2" does not.
    """
    fixed = [n["i"] for n, o in zip(new_rows, old_rows) if n["correct"] and not o["correct"]]
    broke = [n["i"] for n, o in zip(new_rows, old_rows) if o["correct"] and not n["correct"]]
    return fixed, broke


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--shards", required=True, help="directory holding shard<k>.json")
    ap.add_argument("--run-name", default="fed1")
    ap.add_argument("--rounds", type=int, default=5, help="T: federated rounds")
    ap.add_argument("--local-rounds", type=int, default=1, help="E: generate rounds inside each client")
    ap.add_argument("--group", type=int, default=2, help="G: proposers per local round")
    ap.add_argument("--initial-harness", default="bare")
    ap.add_argument("--model", default="deepseek-v4-flash")
    ap.add_argument("--propose-timeout", type=int, default=2700)
    ap.add_argument("--merge-timeout", type=int, default=2700)
    ap.add_argument("--solve-timeout", type=int, default=180)
    ap.add_argument("--budget-lines", type=int, default=150)
    ap.add_argument("--bare-result", default=None)
    ap.add_argument("--max-parallel-clients", type=int, default=5)
    ap.add_argument("--merge-variant", default="holistic", choices=sorted(M.ADOPTION_RULES),
                    help="adoption rule for --aggregate merge (the paper's main method is 'scoped')")
    ap.add_argument("--warm-start", action="store_true",
                    help="round>0: each client starts from ITS OWN previous harness instead of the "
                         "committed global. On the client's shard the two are behaviourally equivalent "
                         "under route aggregation (its home questions are dispatched to its own expert), "
                         "but the proposer sees an editable full program instead of an opaque dispatcher.")
    ap.add_argument("--aggregate", choices=["merge", "select-best", "incremental", "route"], default="merge",
                    help="how a round's client harnesses become the next global. 'merge' has an agent fold "
                         "them into one; 'select-best' just keeps whichever scores highest on the training "
                         "set — the baseline merging has to beat to justify its cost")
    ap.add_argument("--specialist", action="store_true",
                    help="clients evolve as EXPERTS of their own slice rather than toward a generic "
                         "harness — the prerequisite for aggregation to have anything to combine "
                         "(clients otherwise agree 83-94%% and the complementary set is ~7 items)")
    ap.add_argument("--public-val", default=None,
                    help="slice broadcast to every client for CANDIDATE SELECTION. Selecting on the "
                         "client's own shard selects whatever fits those questions, which is how a "
                         "shard-specific hack wins; a shared held-out set cuts that off at the source. "
                         "Private shards still never leave the client. Should be disjoint from --val so "
                         "the server's gate stays independent of what clients selected on.")
    ap.add_argument("--val", default=None,
                    help="cross-set slice used for the ACCEPTANCE GATE (and only for it). Must be a "
                         "REPRESENTATIVE sample of the workload, not another hard slice: the gate has to "
                         "see both what a merge fixes and what it BREAKS. Measured directly — with the gate "
                         "on the (deliberately hard) training shards, three merges were accepted that a "
                         "representative gate rejects, and they cost 12 broken vs 9 fixed items on a "
                         "200-item held-out set. Falls back to the training shards when omitted.")
    ap.add_argument("--supervised", action="store_true",
                    help="train-then-test mode: clients select candidates by measured accuracy on their "
                         "labelled shard, traces state per-question correctness, and a merge is accepted "
                         "only if it matches or beats the broadcast global on the training set")
    args = ap.parse_args()

    shard_dir = Path(args.shards)
    if not shard_dir.is_absolute():                      # cwd already moved (see _ORIG_CWD above)
        shard_dir = _ORIG_CWD / shard_dir
    found = [p for p in shard_dir.glob("shard*.json") if not p.stem.endswith("_details")]
    shards = sorted(found, key=lambda p: int(p.stem.replace("shard", "")))
    if not shards:
        raise SystemExit(f"no shard*.json in {shard_dir}")

    run_dir = PKG_DIR / "logs" / args.run_name
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "config.json").write_text(json.dumps(vars(args) | {"shards": [str(s) for s in shards]},
                                                    indent=2, default=str), encoding="utf-8")
    hist_path = run_dir / "fed_log.jsonl"
    hist = open(hist_path, "w", encoding="utf-8")

    print(f"[fed] {len(shards)} clients x {args.rounds} rounds, E={args.local_rounds} G={args.group}", flush=True)
    print(f"[fed] initial global = {args.initial_harness}", flush=True)

    global_name = args.initial_harness
    lineage = [global_name]
    train_items, train_golds, global_rows = [], [], None
    if args.supervised:
        # The gate measures on --val when given. Clients still evolve on their own (hard) shards; the two
        # distributions differ ON PURPOSE. Hard shards give the proposer room to learn; a representative
        # gate is what notices when a merge trades that learning for damage elsewhere.
        if args.val:
            train_items, train_golds = load_slice(Path(args.val).resolve())
            print(f"[fed] acceptance gate measures on {Path(args.val).name} "
                  f"({len(train_items)} items, representative)", flush=True)
        else:
            train_items, train_golds = training_set(shards)
            print(f"[fed] acceptance gate measures on the training shards — see --val", flush=True)
        global_rows = measure(global_name, train_items, train_golds, str(run_dir), args.solve_timeout)
        print(f"[fed] supervised mode — {global_name} solves "
              f"{sum(r['correct'] for r in global_rows)}/{len(train_items)} of the gate set; a merge "
              f"is accepted when it breaks no more questions than it fixes", flush=True)

    prev_harness = {}                     # client k -> harness it produced last round (for --warm-start)
    for t in range(args.rounds):
        args._round = t
        print(f"\n=== round {t}  broadcast global = {global_name} ===", flush=True)
        started = time.monotonic()

        def start_for(k):
            if args.warm_start and k in prev_harness:
                return prev_harness[k]
            return global_name

        with ThreadPoolExecutor(max_workers=args.max_parallel_clients) as pool:
            futures = [pool.submit(run_client, k, s, start_for(k), args.run_name, args)
                       for k, s in enumerate(shards)]
            results = [f.result() for f in futures]
        results = [r for r in results if r]
        for r in results:
            prev_harness[r["client"]] = r["harness"]
        if not results:
            print(f"[fed] round {t}: every client failed — stopping", flush=True)
            break

        if args.aggregate == "route":
            # Delegation composition — the aggregation this project settled on (RESULTS.md §12). Score
            # every client on the gate, map each home domain to its own expert when the expert is at
            # least as good there as the gate-best client, dispatch everything else to the gate-best.
            # The composite's gate rows are ASSEMBLED from the per-client rows (dispatch is per-db_id
            # deterministic), so the gate costs zero extra solves; the artifact itself is 30 mechanical
            # lines and no merger session runs.
            crows = {}
            for r in results:
                crows[r["harness"]] = measure(r["harness"], train_items, train_golds,
                                              str(run_dir), args.solve_timeout)
            def db_score(rows, db):
                return sum(r["correct"] for r in rows if r["db_id"] == db)
            pool_rows = dict(crows); pool_rows[global_name] = global_rows
            default = max(pool_rows, key=lambda h: sum(r["correct"] for r in pool_rows[h]))
            home = {}
            for r in results:
                dbs = {p[0] for p in json.loads(Path(r["shard"]).read_text(encoding="utf-8"))["cross"]}
                for db in dbs:
                    cand = r["harness"]
                    if db_score(crows[cand], db) >= db_score(pool_rows[default], db):
                        # tie goes to the home expert: its shard covers this domain, the default's
                        # advantage elsewhere says nothing about here
                        if db not in home or db_score(crows[cand], db) > db_score(crows.get(home[db], pool_rows[default]), db):
                            home[db] = cand
            route_rows = [pool_rows[home.get(row["db_id"], default)][i]
                          for i, row in enumerate(global_rows)]
            fixed, broke = compare(route_rows, global_rows)
            score = sum(r["correct"] for r in route_rows)
            out_name = f"fedroute_{args.run_name}_r{t + 1}"
            accepted = bool(len(broke) <= len(fixed) and (fixed or broke))   # identical behaviour -> keep old
            print(f"   [route] gate: {', '.join(f'{h}={sum(x['correct'] for x in v)}' for h, v in pool_rows.items())}", flush=True)
            print(f"   [route] home map: {home}  default={default}", flush=True)
            print(f"   [route] {'ACCEPTED' if accepted else 'REJECTED'} {out_name} "
                  f"(fixed {len(fixed)}, broke {len(broke)}; {score}/{len(train_items)} vs broadcast "
                  f"{sum(r['correct'] for r in global_rows)})", flush=True)
            hist.write(json.dumps({
                "round": t, "broadcast": global_name, "aggregate": "route",
                "home": home, "default": default, "accepted": accepted,
                "gate_scores": {h: sum(x["correct"] for x in v) for h, v in pool_rows.items()},
                "fixed": len(fixed), "broke": len(broke), "gate_score": score,
                "global_after": out_name if accepted else global_name, "clients": results,
                "seconds": round(time.monotonic() - started, 1),
            }) + "\n")
            hist.flush()
            if accepted:
                write_route(out_name, home, default)
                global_name, global_rows = out_name, route_rows
                lineage.append(global_name)
            continue

        if args.aggregate == "select-best":
            # No aggregation: score each client's harness on the whole training set and keep the best,
            # with the broadcast global in the pool so a round can never make things worse. Everything
            # else — sharding, local evolution, broadcast — is identical to the merge path, so a
            # difference in the final numbers is attributable to aggregation alone.
            # Scored on the SAME gate slice the merge variants are gated on. Selecting on the clients'
            # own (hard) training shards instead would give this baseline strictly less information than
            # the aggregators it is compared against, and the comparison would not be about aggregation.
            pool = list(dict.fromkeys([r["harness"] for r in results] + [global_name]))
            scored = {}
            for h in pool:
                rows = (global_rows if h == global_name
                        else measure(h, train_items, train_golds, str(run_dir), args.solve_timeout))
                scored[h] = (sum(r["correct"] for r in rows), rows)
            best = max(scored, key=lambda h: scored[h][0])
            print(f"   [select-best] {', '.join(f'{h}={scored[h][0]}' for h in pool)} -> {best}", flush=True)
            hist.write(json.dumps({
                "round": t, "broadcast": global_name, "aggregate": "select-best",
                "scores": {h: scored[h][0] for h in pool}, "picked": best,
                "global_after": best, "clients": results,
                "seconds": round(time.monotonic() - started, 1),
            }) + "\n")
            hist.flush()
            global_name, global_rows = best, scored[best][1]
            lineage.append(global_name)
            continue

        if args.aggregate == "incremental":
            # Absorb ONE client at a time, gating each step. A single K-way merge can only accept or
            # reject the whole bundle; measured, one client in five was net-negative (+3/-9) and dragged
            # an otherwise useful merge below the broadcast harness. Absorbing one at a time isolates it.
            def local_gain(c):
                p = PKG_DIR / "logs" / c["run"] / "shard_verdicts_b0.json"
                if not p.exists():
                    return 0
                v = json.loads(p.read_text(encoding="utf-8"))["questions"]
                return sum(q["delta"] == "fixed" for q in v) - sum(q["delta"] == "broke" for q in v)
            ordered = sorted(results, key=local_gain, reverse=True)
            cur, cur_rows, kept, steps = global_name, global_rows, 0, []
            for i, c in enumerate(ordered):
                nm = f"inc_{args.run_name}_r{t}_s{i}c{c['client']}"
                ok = M.merge(cur, [c], nm, str(run_dir), args.model, args.merge_timeout,
                             max(40, args.budget_lines // max(1, len(ordered))),
                             gains=client_gains([c]),
                             feedback=("This is an INCREMENTAL aggregation: you are folding in ONE "
                                       "client's delta on top of a global that already absorbed earlier "
                                       "clients. Keep the change minimal and additive — everything "
                                       "already in the base passed a measured gate, so do not "
                                       "restructure or 'improve' it."))
                if not ok:
                    steps.append({"client": c["client"], "kept": False, "reason": "no file"})
                    continue
                rows = measure(nm, train_items, train_golds, str(run_dir), args.solve_timeout)
                f_, b_ = compare(rows, cur_rows)
                keep = len(b_) <= len(f_)
                print(f"   [inc] step {i} client {c['client']}: fixed {len(f_)}, broke {len(b_)} "
                      f"({sum(r['correct'] for r in rows)}/{len(train_items)}) "
                      f"-> {'KEEP' if keep else 'DISCARD'}", flush=True)
                steps.append({"client": c["client"], "candidate": nm, "kept": keep,
                              "fixed": len(f_), "broke": len(b_),
                              "score": sum(r["correct"] for r in rows)})
                if keep:
                    cur, cur_rows, kept = nm, rows, kept + 1
            print(f"   [inc] round {t}: kept {kept}/{len(ordered)} clients -> {cur} "
                  f"({sum(r['correct'] for r in cur_rows)}/{len(train_items)})", flush=True)
            hist.write(json.dumps({"round": t, "broadcast": global_name, "aggregate": "incremental",
                                   "steps": steps, "kept": kept, "global_after": cur,
                                   "gate_score": sum(r["correct"] for r in cur_rows),
                                   "clients": results,
                                   "seconds": round(time.monotonic() - started, 1)}) + "\n")
            hist.flush()
            global_name, global_rows = cur, cur_rows
            lineage.append(global_name)
            continue

        gains = client_gains(results) if args.supervised else ""

        # A rejected merge used to be thrown away with no feedback, so the next round re-ran the same
        # merger against the same base and reproduced the same class of mistake — two of three rounds in
        # the previous run produced nothing at all. Now a failed attempt reports WHICH questions it broke
        # and the merger gets one more try against that evidence.
        accepted, reason, merged_rows, feedback = False, "", None, ""
        accepted_broke = []
        out_name = f"fedglobal_{args.run_name}_r{t + 1}"
        for attempt in range(2 if args.supervised else 1):
            name = out_name if attempt == 0 else f"{out_name}_retry"
            print(f"   [merge] {len(results)} clients -> {name}"
                  f"{' (retry with failure evidence)' if attempt else ''}", flush=True)
            wrote = M.merge(global_name, results, name, str(run_dir), args.model,
                            args.merge_timeout, args.budget_lines, gains=gains, feedback=feedback,
                            variant=args.merge_variant)
            if not wrote:
                reason = "merger produced no file"
                continue
            from .. import bridge
            db0 = bridge.get_db(json.loads(shards[0].read_text(encoding="utf-8"))["cross"][0][0])
            if not M.loadable(name, db0):
                reason = "merged harness does not import"
                feedback = "Your previous attempt did not import. Produce a file that imports cleanly."
                continue
            if not args.supervised:
                ok, tot, _rows = M.smoke(name, str(run_dir), smoke_samples(shards), args.solve_timeout)
                accepted = not (ok == 0 and tot > 0)
                reason = (f"smoke {ok}/{tot} executed cleanly" if accepted else
                          f"merged harness produced no usable result on any of {tot} smoke questions")
                out_name = name
                break
            rows = measure(name, train_items, train_golds, str(run_dir), args.solve_timeout)
            fixed, broke = compare(rows, global_rows)
            reason = (f"fixed {len(fixed)}, broke {len(broke)} "
                      f"({sum(r['correct'] for r in rows)}/{len(train_items)} vs broadcast "
                      f"{sum(r['correct'] for r in global_rows)})")
            if len(broke) <= len(fixed):
                accepted, merged_rows, out_name = True, rows, name
                accepted_broke = list(broke)
                break
            print(f"   [merge] attempt {attempt} rejected — {reason}", flush=True)
            broken_detail = "\n".join(
                f"  - [{rows[i]['db_id']}] {train_items[i][1].partition(chr(10) + 'Hint:')[0].strip()[:150]}\n"
                f"      the broadcast global answered this correctly; your merge produced: {rows[i]['sql'][:200]}"
                for i in broke[:8])
            feedback = (
                f"YOUR PREVIOUS MERGE ATTEMPT WAS REJECTED. It fixed {len(fixed)} questions but BROKE "
                f"{len(broke)} that the broadcast global `{global_name}` already answered correctly:\n"
                f"{broken_detail}\n\n"
                f"Work out what you changed that caused these regressions and do not repeat it. The most "
                f"likely cause is editing behaviour the base already had right — rewriting or reordering "
                f"its existing prompt rules changes the model's behaviour on EVERY question, unlike adding "
                f"a code path that only fires when its condition holds. Prefer adopting fewer mechanisms "
                f"over breaking working ones.")
            out_name = name

        # A merge that fixes more than it breaks still LOSES the questions it broke, permanently — the
        # acceptance rule never asked for them back, so across rounds those losses accumulate and the
        # union of a run's globals ends up ahead of any single one of them. Repair them now, while the
        # counterexamples are available.
        if accepted and accepted_broke and args.supervised:
            rep = f"{out_name}_rep"
            shutil.copyfile(AGENTS_DIR / f"{out_name}.py", AGENTS_DIR / f"{rep}.py")
            cases = [{"db_id": merged_rows[i]["db_id"],
                      "question": train_items[i][1].partition("\nHint:")[0].strip(),
                      "old_sql": global_rows[i]["sql"], "new_sql": merged_rows[i]["sql"]}
                     for i in accepted_broke]
            print(f"   [repair] {len(cases)} regressions -> {rep}", flush=True)
            M.repair(rep, cases, str(run_dir), args.model, args.merge_timeout)
            from .. import bridge as _b
            db0 = _b.get_db(json.loads(shards[0].read_text(encoding="utf-8"))["cross"][0][0])
            if M.loadable(rep, db0):
                rrows = measure(rep, train_items, train_golds, str(run_dir), args.solve_timeout)
                rfixed, rbroke = compare(rrows, global_rows)
                # Take the repair only if it recovers regressions without surrendering the round's gains.
                if len(rbroke) < len(accepted_broke) and len(rfixed) >= len(fixed):
                    print(f"   [repair] ACCEPTED {rep}: broke {len(accepted_broke)} -> {len(rbroke)}, "
                          f"fixed {len(fixed)} -> {len(rfixed)}", flush=True)
                    out_name, merged_rows, reason = rep, rrows, (
                        f"{reason}; repaired to fixed {len(rfixed)}, broke {len(rbroke)}")
                else:
                    print(f"   [repair] rejected: broke {len(accepted_broke)} -> {len(rbroke)}, "
                          f"fixed {len(fixed)} -> {len(rfixed)}; keeping unrepaired merge", flush=True)
            else:
                print(f"   [repair] {rep} does not import; keeping unrepaired merge", flush=True)

        base_lines = len((AGENTS_DIR / f"{global_name}.py").read_text(encoding="utf-8").splitlines())
        new_lines = (len((AGENTS_DIR / f"{out_name}.py").read_text(encoding="utf-8").splitlines())
                     if (AGENTS_DIR / f"{out_name}.py").exists() else None)
        if accepted:
            print(f"   [merge] ACCEPTED {out_name} ({reason}); {base_lines} -> {new_lines} lines", flush=True)
            global_name = out_name
            if merged_rows is not None:
                global_rows = merged_rows
        else:
            print(f"   [merge] REJECTED — {reason}; rolling back to {global_name}", flush=True)
        lineage.append(global_name)

        hist.write(json.dumps({
            "round": t, "broadcast": lineage[-2], "merged_candidate": out_name,
            "accepted": accepted, "reason": reason,
            "base_lines": base_lines, "merged_lines": new_lines,
            "global_after": global_name,
            "clients": results,
            "seconds": round(time.monotonic() - started, 1),
        }) + "\n")
        hist.flush()

    hist.close()
    (run_dir / "final.json").write_text(json.dumps({
        "final_global": global_name, "lineage": lineage,
        "rounds_run": len(lineage) - 1, "fed_log": str(hist_path),
    }, indent=2), encoding="utf-8")
    print(f"\n[fed] final global harness = {global_name}")
    print(f"[fed] lineage: {' -> '.join(lineage)}")
    print(f"[saved] {run_dir}/final.json")


if __name__ == "__main__":
    main()
